name: arduino_serial_api
description: Arduino Serial API is a library for communicating with an Arduino board.
version: 1.0.0
repository: https://github.com/cthurston/arduino_serial_api

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
 path: ^1.8.0-nullsafety.3
 dart_serial_port: 0.0.4+1

dev_dependencies:
  pedantic: ^1.9.0
  test:
